### ISSUE TITLE
想问问作者是怎么分析数据的呢？？

### ISSUE THREAD

**Issue by tianshaokai** [Assassinss/Interessant#1]
我最近想分析一下快手app，下载了fiddler 不知道怎么分析

**Comment by Assassinss** [comment]
@tianshaokai Fiddler 网上教程不少，可以 Google 下，我当时是先登录开眼视频 App 然后再用 Fiddler 抓数据，由于开眼视频用的是 Http 传输协议所以抓取数据比较简单。

**Comment by tianshaokai** [comment]
我也看到api，可是把api 扔到 浏览器里就返回错误日志，我会用这工具，就是看到这api 不知道怎么分析，不知道怎么弄了

**Comment by Assassinss** [comment]
@tianshaokai 错误日志的话可能缺少参数，还是参数错误了，可能是请求方式错了？，可以用 postman 请求测试看看。

**Comment by tianshaokai** [comment]
测试了依然错误，真不知道你们是怎么搞的，

**Comment by Assassinss** [comment]
@tianshaokai 快手 App 我也没分析过，具体的细节我也不清楚，帮不了忙了哈。

**Comment by 90TangJie1028** [comment]
@Assassinss  楼主，首先我是新手，想学下RxJava+Retrofit+MVP模式的一个用，不过看了你的代码，好多是lambda表达式，看的是欲仙欲死，有没有简化版的呀？谢谢了（330735830@qq.com）

**Comment by Assassinss** [comment]
@90TangJie1028 并没有什么简化版，你要是觉得 lambda 比较难看可以在 gradle 中去掉 complileOptions ，然后将 lambda 代码换回匿名内部类的方式就行了。
