### ISSUE TITLE
源代码资源文件名中有大写导致编译失败

### ISSUE THREAD

**Issue by fishwjy** [Assassinss/Interessant#3]
源代码资源文件中seekBar为大写的B，导致编译失败
但源代码代码中使用的地方都是小写的，改为小写肯定是可以编译的
只是比较好奇作者用大写的文件名也能编译吗？如果是，有什么小技巧？望不吝赐教，多谢😄

**Comment by Assassinss** [comment]
@fishwjy 实际上我本地代码是小写，至于为什么 push 到 Github 是大写我也不太清楚。

**Comment by fishwjy** [comment]
好的，明白了
