### ISSUE TITLE
MainActivity中RxRecyclerView.scrollStateChanges的疑问？

### ISSUE THREAD

**Issue by LoveqLRC** [Assassinss/Interessant#4]
根据RxRecyclerView.scrollStateChanges的注释会保持RecyclerView的强引用，是否应该在MainActivity destory  unsubscribe the subscription？

**Comment by Assassinss** [comment]
@LoveqLRC 不用加，因为已经加了RxLifecycle绑定生命周期了

**Comment by LoveqLRC** [comment]
那DailyViewBinder中RxView.clicks呢，这种是不需要解除绑定的吗？

**Comment by Assassinss** [comment]
@LoveqLRC 写上会更好，这代码好久没维护，所以难免有很多写的不好的地方

**Comment by LoveqLRC** [comment]
好吧，哥们你是怎么学习的，感觉你会很多啊~~，RN也玩的6

**Comment by Assassinss** [comment]
@LoveqLRC 多写代码吧，其实我也懂得不多
